name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t awaismohammad23/assignment_4_q1:latest -f Dockerfile .
        docker login -u awaismohammad23 -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image to DockerHub
      run: docker push awaismohammad23/ubuntu_assignment_4_q1:latest

