name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        FROM python:3.10.13-alpine
        LABEL name="Python Application" \
        maintainer="Awais Mohammad <awaismadad@gmail.com>" \
        summary="A Sample Python application"
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install -r 'requirements.txt'
        EXPOSE 8080
        COPY . ./
        CMD [ "python", "./app.py" ]

    - name: Push Docker Image to DockerHub
      run: docker push awaismohammad23/ubuntu_assignment_4:latest

